/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.end_elemetn.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.end_elemetn.item.*;
import net.mcreator.end_elemetn.EndElemetnMod;

public class EndElemetnModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(EndElemetnMod.MODID);
	public static final DeferredItem<Item> SHULKER_HELMET;
	public static final DeferredItem<Item> SHULKER_CHESTPLATE;
	public static final DeferredItem<Item> SHULKER_LEGGINGS;
	public static final DeferredItem<Item> SHULKER_BOOTS;
	public static final DeferredItem<Item> END_COBBELSTONE;
	public static final DeferredItem<Item> END_MESHFADES_STONE;
	public static final DeferredItem<Item> GREEN_END_STONE;
	public static final DeferredItem<Item> GREEN_END_COBBLESTONE;
	public static final DeferredItem<Item> DIRTY_END_COBBLESTONE;
	public static final DeferredItem<Item> CRACKED_GREEN_ENDCOBBLESTONE;
	public static final DeferredItem<Item> ENDWILD_GRASS;
	public static final DeferredItem<Item> ENDER_WOOD;
	public static final DeferredItem<Item> ENDER_LOG;
	public static final DeferredItem<Item> ENDER_PLANKS;
	public static final DeferredItem<Item> ENDER_LEAVES;
	public static final DeferredItem<Item> ENDER_STAIRS;
	public static final DeferredItem<Item> ENDER_SLAB;
	public static final DeferredItem<Item> ENDER_FENCE;
	public static final DeferredItem<Item> ENDER_FENCE_GATE;
	public static final DeferredItem<Item> ENDER_PRESSURE_PLATE;
	public static final DeferredItem<Item> ENDER_BUTTON;
	public static final DeferredItem<Item> END_FERN;
	public static final DeferredItem<Item> END_TALL_GRESS;
	public static final DeferredItem<Item> END_GRASS;
	public static final DeferredItem<Item> END_WILD_CORAL;
	public static final DeferredItem<Item> ENDSTONE_GRASS;
	public static final DeferredItem<Item> ENDSTONE_BLOSSOM_GRASS;
	public static final DeferredItem<Item> END_VINES;
	public static final DeferredItem<Item> END_MUD_BLOCK;
	public static final DeferredItem<Item> END_MUD_BUCKET;
	public static final DeferredItem<Item> END_WILD_TREE_SAPLING;
	public static final DeferredItem<Item> DRY_CHORUS_FLOWER;
	public static final DeferredItem<Item> DRY_CHORUS_PLANT;
	public static final DeferredItem<Item> END_MESH_PICK;
	public static final DeferredItem<Item> ENDER_WOOD_STAIRS;
	public static final DeferredItem<Item> MUDDY_ENDCOBBLESTONE;
	public static final DeferredItem<Item> MUG_GASER_BLOCK;
	public static final DeferredItem<Item> ENDSTONE_DUST;
	public static final DeferredItem<Item> ENDER_DOOR;
	public static final DeferredItem<Item> ENDER_TRAPDOOR;
	public static final DeferredItem<Item> END_WILD_FLOWER;
	public static final DeferredItem<Item> SNARELINGWEB;
	public static final DeferredItem<Item> SNARELINGBLOB;
	public static final DeferredItem<Item> VOID_LIQUID_BUCKET;
	public static final DeferredItem<Item> VOID_BLOCK;
	public static final DeferredItem<Item> VOID_FLAME;
	public static final DeferredItem<Item> WATCHLING_SPAWN_EGG;
	public static final DeferredItem<Item> SNARELING_SPAWN_EGG;
	public static final DeferredItem<Item> BLASTLING_SPAWN_EGG;
	public static final DeferredItem<Item> LURELING_SPAWN_EGG;
	public static final DeferredItem<Item> TRUMPLING_SPAWN_EGG;
	public static final DeferredItem<Item> ENDERSENT_SPAWN_EGG;
	public static final DeferredItem<Item> EYED_ENDERSENT_SPAWN_EGG;
	public static final DeferredItem<Item> END_WARPED_GRASS;
	public static final DeferredItem<Item> WARPED_LOG;
	public static final DeferredItem<Item> WARPED_WOOD;
	public static final DeferredItem<Item> WARPED_PLANKS;
	public static final DeferredItem<Item> WARPED_LEAVES;
	public static final DeferredItem<Item> WARPED_STAIRS;
	public static final DeferredItem<Item> WARPED_SLAB;
	public static final DeferredItem<Item> WARPED_FENCE;
	public static final DeferredItem<Item> WARPED_FENCE_GATE;
	public static final DeferredItem<Item> WARPED_PRESSURE_PLATE;
	public static final DeferredItem<Item> WARPED_BUTTON;
	public static final DeferredItem<Item> WARPED_FLOOR_ROOTS;
	public static final DeferredItem<Item> CHORUS_GRASS;
	public static final DeferredItem<Item> CHORUS_LOG;
	public static final DeferredItem<Item> CHORUS_WOOD;
	public static final DeferredItem<Item> CHORUS_PLANKS;
	public static final DeferredItem<Item> CHORUS_LEAVES;
	public static final DeferredItem<Item> CHORUS_STAIRS;
	public static final DeferredItem<Item> CHORUS_SLAB;
	public static final DeferredItem<Item> CHORUS_FENCE;
	public static final DeferredItem<Item> CHORUS_FENCE_GATE;
	public static final DeferredItem<Item> CHORUS_PRESSURE_PLATE;
	public static final DeferredItem<Item> CHORUS_BUTTON;
	public static final DeferredItem<Item> CHORUS_VINES;
	public static final DeferredItem<Item> CHORUS_BLOSSOM_GRASS;
	public static final DeferredItem<Item> CHORUS_PLANT;
	public static final DeferredItem<Item> TALL_CHORUS_PLANT;
	public static final DeferredItem<Item> CHORUS_SHROOM;
	public static final DeferredItem<Item> TALL_CHORUS_BLOSSOM_GRASS;
	public static final DeferredItem<Item> ENDERITE_ORE;
	public static final DeferredItem<Item> TITANIUM_ORE;
	public static final DeferredItem<Item> ENDERITE;
	public static final DeferredItem<Item> RAW_TITANIUM;
	public static final DeferredItem<Item> TITANIUM_INGOT;
	public static final DeferredItem<Item> TITANIUM_NUGGET;
	public static final DeferredItem<Item> TITANIUM_COIN;
	public static final DeferredItem<Item> COMMPREST_VOID;
	public static final DeferredItem<Item> CRACKED_ENDSTONE_BRICKS;
	public static final DeferredItem<Item> CHISELED_ENDSTONE_BRICKS;
	public static final DeferredItem<Item> ENDSTONE_TILES;
	public static final DeferredItem<Item> POLISHED_ENDSTONE;
	public static final DeferredItem<Item> ENDSTONE_PILLAR;
	public static final DeferredItem<Item> ARCH_ENDSTONE_PILLAR;
	public static final DeferredItem<Item> SMOOTH_PURPUR;
	public static final DeferredItem<Item> CRACKED_PURPUR;
	public static final DeferredItem<Item> PURPUR_TILES;
	public static final DeferredItem<Item> CUBET_PURPUR_TILES;
	public static final DeferredItem<Item> CHISELED_PURPUR;
	public static final DeferredItem<Item> CRYSTALLIZED_PURPUR;
	public static final DeferredItem<Item> TRADLING_SPAWN_EGG;
	public static final DeferredItem<Item> ENDERBABY_SPAWN_EGG;
	public static final DeferredItem<Item> ENDSTONE_LOOTBOX;
	public static final DeferredItem<Item> TITANIUM_LOOTBOX;
	public static final DeferredItem<Item> ENDERITE_LOOTBOX;
	public static final DeferredItem<Item> WEAPON_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> SHULKER_UPGRADER_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> ENTERNAL_UPGRADER_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> PURPUR_WALL;
	public static final DeferredItem<Item> END_CITY_VAULT;
	public static final DeferredItem<Item> END_CITY_KEY;
	public static final DeferredItem<Item> ENDERITE_HELMET;
	public static final DeferredItem<Item> ENDERITE_CHESTPLATE;
	public static final DeferredItem<Item> ENDERITE_LEGGINGS;
	public static final DeferredItem<Item> ENDERITE_BOOTS;
	public static final DeferredItem<Item> ENDERITHE_SHOVEL;
	public static final DeferredItem<Item> ENDERITHE_SWORD;
	public static final DeferredItem<Item> ENDERITHE_PICKAXE;
	public static final DeferredItem<Item> ENDERITHE_AXE;
	public static final DeferredItem<Item> ENDERITHE_HOE;
	public static final DeferredItem<Item> ENDERITHE_SCYTHE;
	public static final DeferredItem<Item> ENDERITHE_BOW;
	public static final DeferredItem<Item> ENDERITHE_PICKAXE_SHARD;
	public static final DeferredItem<Item> ENDERITHE_AXE_SHARD;
	public static final DeferredItem<Item> ENDERITHE_HOE_SHARD;
	public static final DeferredItem<Item> ENDERITHE_SWORD_SHARD;
	public static final DeferredItem<Item> ENDERITHE_SHOWEL_SHARD;
	public static final DeferredItem<Item> ENDERITHE_BOW_SHARD;
	public static final DeferredItem<Item> ENDERITHE_SCYTHE_SHARD;
	public static final DeferredItem<Item> ENDERITHE_HAMMER;
	public static final DeferredItem<Item> ENDERITHE_HAMMER_SHARD;
	public static final DeferredItem<Item> END_SPAWNER;
	public static final DeferredItem<Item> END_FIRE;
	public static final DeferredItem<Item> METEOR_SCRAP;
	public static final DeferredItem<Item> UPGRADED_ENDERITHE_INGOT;
	public static final DeferredItem<Item> ENDERITHE_INGOT;
	public static final DeferredItem<Item> METEOR_DEBRIS;
	public static final DeferredItem<Item> CELESTIAN_GUARD_SPAWN_EGG;
	public static final DeferredItem<Item> TITANIUM_PEDESTAL;
	public static final DeferredItem<Item> STAR;
	public static final DeferredItem<Item> TITANIUM_BLOCK;
	public static final DeferredItem<Item> SHADOWLING_SPAWN_EGG;
	public static final DeferredItem<Item> SHADOW_GRASS;
	public static final DeferredItem<Item> PILLARS_OF_SHADOW_WOOD;
	public static final DeferredItem<Item> UNKNOWN_BLOCK;
	public static final DeferredItem<Item> ENTERNAL_RAW_ORE;
	public static final DeferredItem<Item> NECROSENT_SPAWN_EGG;
	public static final DeferredItem<Item> CRYING_WATCHLING_SPAWN_EGG;
	public static final DeferredItem<Item> CRYING_SNARELING_SPAWN_EGG;
	public static final DeferredItem<Item> CRYING_BLASTLING_SPAWN_EGG;
	public static final DeferredItem<Item> THE_END_SHARD;
	public static final DeferredItem<Item> BLASTLING_SHOOT;
	public static final DeferredItem<Item> LURE;
	public static final DeferredItem<Item> WATCHLING_EYE;
	public static final DeferredItem<Item> THUMPET;
	public static final DeferredItem<Item> FUSELING;
	public static final DeferredItem<Item> SNARE_STRING;
	public static final DeferredItem<Item> CORRUPTED_BEACON;
	public static final DeferredItem<Item> DRAGON_FRUIT_GROW;
	public static final DeferredItem<Item> DRAGON_FRUIT;
	public static final DeferredItem<Item> DRACORA_PALM_LOG;
	public static final DeferredItem<Item> DRACORA_PALM_WOOD;
	public static final DeferredItem<Item> DRACORA_PALM_PLANKS;
	public static final DeferredItem<Item> DRACORA_PALM_LEAVES;
	public static final DeferredItem<Item> DRACORA_PALM_STAIRS;
	public static final DeferredItem<Item> DRACORA_PALM_SLAB;
	public static final DeferredItem<Item> DRACORA_PALM_FENCE;
	public static final DeferredItem<Item> DRACORA_PALM_FENCE_GATE;
	public static final DeferredItem<Item> DRACORA_PALM_PRESSURE_PLATE;
	public static final DeferredItem<Item> DRACORA_PALM_BUTTON;
	public static final DeferredItem<Item> DRACORA_GRASS;
	public static final DeferredItem<Item> ENDER_JELLYFISH_SPAWN_EGG;
	public static final DeferredItem<Item> VENGEFUL_HEART_OF_ENDER_SPAWN_EGG;
	public static final DeferredItem<Item> MOSSY_ENDSTONE_BRICKS;
	public static final DeferredItem<Item> CRACKED_CHORUS_PLANKS;
	public static final DeferredItem<Item> DIRTY_CHORUS_PLANKS;
	public static final DeferredItem<Item> CORN_STAGE_0;
	public static final DeferredItem<Item> CORN_STAGE_1;
	public static final DeferredItem<Item> CORN_STAGE_2;
	public static final DeferredItem<Item> CORN_STAGE_3;
	public static final DeferredItem<Item> CORN_SEEDS;
	public static final DeferredItem<Item> CORN;
	public static final DeferredItem<Item> DIMENSIONAL_CUTTER;
	public static final DeferredItem<Item> SHARD_OF_EYE_OF_TELEPORTATION;
	public static final DeferredItem<Item> HOLE_IN_REALITY;
	public static final DeferredItem<Item> END_BOTTLE;
	public static final DeferredItem<Item> FULL_END_BOTTLE;
	public static final DeferredItem<Item> UNSTABLE_HOLE_IN_REALITY;
	public static final DeferredItem<Item> EYE_OF_TELEPORTATION;
	public static final DeferredItem<Item> ENDSTONE_KEY;
	public static final DeferredItem<Item> END_SOULFUL_KEY;
	public static final DeferredItem<Item> WOODEN_HAMMER;
	public static final DeferredItem<Item> STONE_HAMMER;
	public static final DeferredItem<Item> IRON_HAMMER;
	public static final DeferredItem<Item> GOLDEN_HAMMER;
	public static final DeferredItem<Item> DIAMOND_HAMMER;
	public static final DeferredItem<Item> NETHERITE_HAMMER;
	public static final DeferredItem<Item> WOODEN_SCYTH;
	public static final DeferredItem<Item> STONE_SCYTH;
	public static final DeferredItem<Item> IRON_SCYTH;
	public static final DeferredItem<Item> GOLDEN_SCYTH;
	public static final DeferredItem<Item> DIAMOND_SCYTH;
	public static final DeferredItem<Item> NETHERITE_SCYTH;
	static {
		SHULKER_HELMET = REGISTRY.register("shulker_helmet", ShulkerItem.Helmet::new);
		SHULKER_CHESTPLATE = REGISTRY.register("shulker_chestplate", ShulkerItem.Chestplate::new);
		SHULKER_LEGGINGS = REGISTRY.register("shulker_leggings", ShulkerItem.Leggings::new);
		SHULKER_BOOTS = REGISTRY.register("shulker_boots", ShulkerItem.Boots::new);
		END_COBBELSTONE = block(EndElemetnModBlocks.END_COBBELSTONE);
		END_MESHFADES_STONE = block(EndElemetnModBlocks.END_MESHFADES_STONE);
		GREEN_END_STONE = block(EndElemetnModBlocks.GREEN_END_STONE);
		GREEN_END_COBBLESTONE = block(EndElemetnModBlocks.GREEN_END_COBBLESTONE);
		DIRTY_END_COBBLESTONE = block(EndElemetnModBlocks.DIRTY_END_COBBLESTONE);
		CRACKED_GREEN_ENDCOBBLESTONE = block(EndElemetnModBlocks.CRACKED_GREEN_ENDCOBBLESTONE);
		ENDWILD_GRASS = block(EndElemetnModBlocks.ENDWILD_GRASS);
		ENDER_WOOD = block(EndElemetnModBlocks.ENDER_WOOD);
		ENDER_LOG = block(EndElemetnModBlocks.ENDER_LOG);
		ENDER_PLANKS = block(EndElemetnModBlocks.ENDER_PLANKS);
		ENDER_LEAVES = block(EndElemetnModBlocks.ENDER_LEAVES);
		ENDER_STAIRS = block(EndElemetnModBlocks.ENDER_STAIRS);
		ENDER_SLAB = block(EndElemetnModBlocks.ENDER_SLAB);
		ENDER_FENCE = block(EndElemetnModBlocks.ENDER_FENCE);
		ENDER_FENCE_GATE = block(EndElemetnModBlocks.ENDER_FENCE_GATE);
		ENDER_PRESSURE_PLATE = block(EndElemetnModBlocks.ENDER_PRESSURE_PLATE);
		ENDER_BUTTON = block(EndElemetnModBlocks.ENDER_BUTTON);
		END_FERN = doubleBlock(EndElemetnModBlocks.END_FERN);
		END_TALL_GRESS = doubleBlock(EndElemetnModBlocks.END_TALL_GRESS);
		END_GRASS = block(EndElemetnModBlocks.END_GRASS);
		END_WILD_CORAL = block(EndElemetnModBlocks.END_WILD_CORAL);
		ENDSTONE_GRASS = block(EndElemetnModBlocks.ENDSTONE_GRASS);
		ENDSTONE_BLOSSOM_GRASS = block(EndElemetnModBlocks.ENDSTONE_BLOSSOM_GRASS);
		END_VINES = block(EndElemetnModBlocks.END_VINES);
		END_MUD_BLOCK = block(EndElemetnModBlocks.END_MUD_BLOCK);
		END_MUD_BUCKET = REGISTRY.register("end_mud_bucket", EndMudItem::new);
		END_WILD_TREE_SAPLING = block(EndElemetnModBlocks.END_WILD_TREE_SAPLING);
		DRY_CHORUS_FLOWER = block(EndElemetnModBlocks.DRY_CHORUS_FLOWER);
		DRY_CHORUS_PLANT = block(EndElemetnModBlocks.DRY_CHORUS_PLANT);
		END_MESH_PICK = block(EndElemetnModBlocks.END_MESH_PICK);
		ENDER_WOOD_STAIRS = block(EndElemetnModBlocks.ENDER_WOOD_STAIRS);
		MUDDY_ENDCOBBLESTONE = block(EndElemetnModBlocks.MUDDY_ENDCOBBLESTONE);
		MUG_GASER_BLOCK = block(EndElemetnModBlocks.MUG_GASER_BLOCK);
		ENDSTONE_DUST = block(EndElemetnModBlocks.ENDSTONE_DUST);
		ENDER_DOOR = doubleBlock(EndElemetnModBlocks.ENDER_DOOR);
		ENDER_TRAPDOOR = block(EndElemetnModBlocks.ENDER_TRAPDOOR);
		END_WILD_FLOWER = block(EndElemetnModBlocks.END_WILD_FLOWER);
		SNARELINGWEB = block(EndElemetnModBlocks.SNARELINGWEB);
		SNARELINGBLOB = REGISTRY.register("snarelingblob", SnarelingblobItem::new);
		VOID_LIQUID_BUCKET = REGISTRY.register("void_liquid_bucket", VoidLiquidItem::new);
		VOID_BLOCK = block(EndElemetnModBlocks.VOID_BLOCK);
		VOID_FLAME = block(EndElemetnModBlocks.VOID_FLAME);
		WATCHLING_SPAWN_EGG = REGISTRY.register("watchling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.WATCHLING, -15592942, -2809881, new Item.Properties()));
		SNARELING_SPAWN_EGG = REGISTRY.register("snareling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.SNARELING, -15592942, -5570816, new Item.Properties()));
		BLASTLING_SPAWN_EGG = REGISTRY.register("blastling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.BLASTLING, -15592942, -364300, new Item.Properties()));
		LURELING_SPAWN_EGG = REGISTRY.register("lureling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.LURELING, -15592942, -46382, new Item.Properties()));
		TRUMPLING_SPAWN_EGG = REGISTRY.register("trumpling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.TRUMPLING, -15592942, -14735049, new Item.Properties()));
		ENDERSENT_SPAWN_EGG = REGISTRY.register("endersent_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.ENDERSENT, -15856114, -15704488, new Item.Properties()));
		EYED_ENDERSENT_SPAWN_EGG = REGISTRY.register("eyed_endersent_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.EYED_ENDERSENT, -15856114, -15704488, new Item.Properties()));
		END_WARPED_GRASS = block(EndElemetnModBlocks.END_WARPED_GRASS);
		WARPED_LOG = block(EndElemetnModBlocks.WARPED_LOG);
		WARPED_WOOD = block(EndElemetnModBlocks.WARPED_WOOD);
		WARPED_PLANKS = block(EndElemetnModBlocks.WARPED_PLANKS);
		WARPED_LEAVES = block(EndElemetnModBlocks.WARPED_LEAVES);
		WARPED_STAIRS = block(EndElemetnModBlocks.WARPED_STAIRS);
		WARPED_SLAB = block(EndElemetnModBlocks.WARPED_SLAB);
		WARPED_FENCE = block(EndElemetnModBlocks.WARPED_FENCE);
		WARPED_FENCE_GATE = block(EndElemetnModBlocks.WARPED_FENCE_GATE);
		WARPED_PRESSURE_PLATE = block(EndElemetnModBlocks.WARPED_PRESSURE_PLATE);
		WARPED_BUTTON = block(EndElemetnModBlocks.WARPED_BUTTON);
		WARPED_FLOOR_ROOTS = block(EndElemetnModBlocks.WARPED_FLOOR_ROOTS);
		CHORUS_GRASS = block(EndElemetnModBlocks.CHORUS_GRASS);
		CHORUS_LOG = block(EndElemetnModBlocks.CHORUS_LOG);
		CHORUS_WOOD = block(EndElemetnModBlocks.CHORUS_WOOD);
		CHORUS_PLANKS = block(EndElemetnModBlocks.CHORUS_PLANKS);
		CHORUS_LEAVES = block(EndElemetnModBlocks.CHORUS_LEAVES);
		CHORUS_STAIRS = block(EndElemetnModBlocks.CHORUS_STAIRS);
		CHORUS_SLAB = block(EndElemetnModBlocks.CHORUS_SLAB);
		CHORUS_FENCE = block(EndElemetnModBlocks.CHORUS_FENCE);
		CHORUS_FENCE_GATE = block(EndElemetnModBlocks.CHORUS_FENCE_GATE);
		CHORUS_PRESSURE_PLATE = block(EndElemetnModBlocks.CHORUS_PRESSURE_PLATE);
		CHORUS_BUTTON = block(EndElemetnModBlocks.CHORUS_BUTTON);
		CHORUS_VINES = block(EndElemetnModBlocks.CHORUS_VINES);
		CHORUS_BLOSSOM_GRASS = block(EndElemetnModBlocks.CHORUS_BLOSSOM_GRASS);
		CHORUS_PLANT = block(EndElemetnModBlocks.CHORUS_PLANT);
		TALL_CHORUS_PLANT = doubleBlock(EndElemetnModBlocks.TALL_CHORUS_PLANT);
		CHORUS_SHROOM = block(EndElemetnModBlocks.CHORUS_SHROOM);
		TALL_CHORUS_BLOSSOM_GRASS = doubleBlock(EndElemetnModBlocks.TALL_CHORUS_BLOSSOM_GRASS);
		ENDERITE_ORE = block(EndElemetnModBlocks.ENDERITE_ORE);
		TITANIUM_ORE = block(EndElemetnModBlocks.TITANIUM_ORE);
		ENDERITE = REGISTRY.register("enderite", EnderiteItem::new);
		RAW_TITANIUM = REGISTRY.register("raw_titanium", RawTitaniumItem::new);
		TITANIUM_INGOT = REGISTRY.register("titanium_ingot", TitaniumIngotItem::new);
		TITANIUM_NUGGET = REGISTRY.register("titanium_nugget", TitaniumNuggetItem::new);
		TITANIUM_COIN = REGISTRY.register("titanium_coin", TitaniumCoinItem::new);
		COMMPREST_VOID = block(EndElemetnModBlocks.COMMPREST_VOID);
		CRACKED_ENDSTONE_BRICKS = block(EndElemetnModBlocks.CRACKED_ENDSTONE_BRICKS);
		CHISELED_ENDSTONE_BRICKS = block(EndElemetnModBlocks.CHISELED_ENDSTONE_BRICKS);
		ENDSTONE_TILES = block(EndElemetnModBlocks.ENDSTONE_TILES);
		POLISHED_ENDSTONE = block(EndElemetnModBlocks.POLISHED_ENDSTONE);
		ENDSTONE_PILLAR = block(EndElemetnModBlocks.ENDSTONE_PILLAR);
		ARCH_ENDSTONE_PILLAR = block(EndElemetnModBlocks.ARCH_ENDSTONE_PILLAR);
		SMOOTH_PURPUR = block(EndElemetnModBlocks.SMOOTH_PURPUR);
		CRACKED_PURPUR = block(EndElemetnModBlocks.CRACKED_PURPUR);
		PURPUR_TILES = block(EndElemetnModBlocks.PURPUR_TILES);
		CUBET_PURPUR_TILES = block(EndElemetnModBlocks.CUBET_PURPUR_TILES);
		CHISELED_PURPUR = block(EndElemetnModBlocks.CHISELED_PURPUR);
		CRYSTALLIZED_PURPUR = REGISTRY.register("crystallized_purpur", CrystallizedPurpurItem::new);
		TRADLING_SPAWN_EGG = REGISTRY.register("tradling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.TRADLING, -15395563, -5289500, new Item.Properties()));
		ENDERBABY_SPAWN_EGG = REGISTRY.register("enderbaby_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.ENDERBABY, -15921907, -29975, new Item.Properties()));
		ENDSTONE_LOOTBOX = REGISTRY.register("endstone_lootbox", EndstoneLootboxItem::new);
		TITANIUM_LOOTBOX = REGISTRY.register("titanium_lootbox", TitaniumLootboxItem::new);
		ENDERITE_LOOTBOX = REGISTRY.register("enderite_lootbox", EnderiteLootboxItem::new);
		WEAPON_SMITHING_TEMPLATE = REGISTRY.register("weapon_smithing_template", WeaponSmeathingTemplateItem::new);
		SHULKER_UPGRADER_SMITHING_TEMPLATE = REGISTRY.register("shulker_upgrader_smithing_template", ShulkerUpgraderSmithingTemplateItem::new);
		ENTERNAL_UPGRADER_SMITHING_TEMPLATE = REGISTRY.register("enternal_upgrader_smithing_template", EnternalUpgraderSmithingTemplateItem::new);
		PURPUR_WALL = block(EndElemetnModBlocks.PURPUR_WALL);
		END_CITY_VAULT = block(EndElemetnModBlocks.END_CITY_VAULT);
		END_CITY_KEY = REGISTRY.register("end_city_key", EndCityKeyItem::new);
		ENDERITE_HELMET = REGISTRY.register("enderite_helmet", EnternalItem.Helmet::new);
		ENDERITE_CHESTPLATE = REGISTRY.register("enderite_chestplate", EnternalItem.Chestplate::new);
		ENDERITE_LEGGINGS = REGISTRY.register("enderite_leggings", EnternalItem.Leggings::new);
		ENDERITE_BOOTS = REGISTRY.register("enderite_boots", EnternalItem.Boots::new);
		ENDERITHE_SHOVEL = REGISTRY.register("enderithe_shovel", EnternalShovelItem::new);
		ENDERITHE_SWORD = REGISTRY.register("enderithe_sword", EnternalSwordItem::new);
		ENDERITHE_PICKAXE = REGISTRY.register("enderithe_pickaxe", EnternalPickaxeItem::new);
		ENDERITHE_AXE = REGISTRY.register("enderithe_axe", EnternalAxeItem::new);
		ENDERITHE_HOE = REGISTRY.register("enderithe_hoe", EnternalHoeItem::new);
		ENDERITHE_SCYTHE = REGISTRY.register("enderithe_scythe", EnternalScytheItem::new);
		ENDERITHE_BOW = REGISTRY.register("enderithe_bow", EnternalBowItem::new);
		ENDERITHE_PICKAXE_SHARD = REGISTRY.register("enderithe_pickaxe_shard", EnternalPickaxeShardItem::new);
		ENDERITHE_AXE_SHARD = REGISTRY.register("enderithe_axe_shard", EnternalAxeShardItem::new);
		ENDERITHE_HOE_SHARD = REGISTRY.register("enderithe_hoe_shard", EnternalHoeShardItem::new);
		ENDERITHE_SWORD_SHARD = REGISTRY.register("enderithe_sword_shard", EnternalSwordShardItem::new);
		ENDERITHE_SHOWEL_SHARD = REGISTRY.register("enderithe_showel_shard", EnternalShowelShardItem::new);
		ENDERITHE_BOW_SHARD = REGISTRY.register("enderithe_bow_shard", EnternalBowShardItem::new);
		ENDERITHE_SCYTHE_SHARD = REGISTRY.register("enderithe_scythe_shard", EnternalScytheShardItem::new);
		ENDERITHE_HAMMER = REGISTRY.register("enderithe_hammer", EnternalHammerItem::new);
		ENDERITHE_HAMMER_SHARD = REGISTRY.register("enderithe_hammer_shard", EnternalHammerShardItem::new);
		END_SPAWNER = block(EndElemetnModBlocks.END_SPAWNER);
		END_FIRE = block(EndElemetnModBlocks.END_FIRE);
		METEOR_SCRAP = REGISTRY.register("meteor_scrap", ChorusScrapItem::new);
		UPGRADED_ENDERITHE_INGOT = REGISTRY.register("upgraded_enderithe_ingot", UpgradedEnternalShardItem::new);
		ENDERITHE_INGOT = REGISTRY.register("enderithe_ingot", EnternalShardItem::new);
		METEOR_DEBRIS = block(EndElemetnModBlocks.METEOR_DEBRIS);
		CELESTIAN_GUARD_SPAWN_EGG = REGISTRY.register("celestian_guard_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.CELESTIAN_GUARD, -9743246, -9476750, new Item.Properties()));
		TITANIUM_PEDESTAL = block(EndElemetnModBlocks.TITANIUM_PEDESTAL);
		STAR = REGISTRY.register("star", StarItem::new);
		TITANIUM_BLOCK = block(EndElemetnModBlocks.TITANIUM_BLOCK);
		SHADOWLING_SPAWN_EGG = REGISTRY.register("shadowling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.SHADOWLING, -16121826, -16711670, new Item.Properties()));
		SHADOW_GRASS = block(EndElemetnModBlocks.SHADOW_GRASS);
		PILLARS_OF_SHADOW_WOOD = block(EndElemetnModBlocks.PILLARS_OF_SHADOW_WOOD);
		UNKNOWN_BLOCK = block(EndElemetnModBlocks.UNKNOWN_BLOCK);
		ENTERNAL_RAW_ORE = REGISTRY.register("enternal_raw_ore", EnternalRawOreItem::new);
		NECROSENT_SPAWN_EGG = REGISTRY.register("necrosent_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.NECROSENT, -16250871, -9769729, new Item.Properties()));
		CRYING_WATCHLING_SPAWN_EGG = REGISTRY.register("crying_watchling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.CRYING_WATCHLING, -15592942, -14695961, new Item.Properties()));
		CRYING_SNARELING_SPAWN_EGG = REGISTRY.register("crying_snareling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.CRYING_SNARELING, -15592942, -16711713, new Item.Properties()));
		CRYING_BLASTLING_SPAWN_EGG = REGISTRY.register("crying_blastling_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.CRYING_BLASTLING, -15592942, -9376262, new Item.Properties()));
		THE_END_SHARD = REGISTRY.register("the_end_shard", TheEndShardItem::new);
		BLASTLING_SHOOT = REGISTRY.register("blastling_shoot", BlastlingShootItem::new);
		LURE = REGISTRY.register("lure", LureItem::new);
		WATCHLING_EYE = REGISTRY.register("watchling_eye", WatchlingEyeItem::new);
		THUMPET = REGISTRY.register("thumpet", ThumpetItem::new);
		FUSELING = REGISTRY.register("fuseling", FuselingItem::new);
		SNARE_STRING = REGISTRY.register("snare_string", SnareStringItem::new);
		CORRUPTED_BEACON = REGISTRY.register("corrupted_beacon", CorruptedBeaconItem::new);
		DRAGON_FRUIT_GROW = block(EndElemetnModBlocks.DRAGON_FRUIT_GROW);
		DRAGON_FRUIT = REGISTRY.register("dragon_fruit", DragonFruitItem::new);
		DRACORA_PALM_LOG = block(EndElemetnModBlocks.DRACORA_PALM_LOG);
		DRACORA_PALM_WOOD = block(EndElemetnModBlocks.DRACORA_PALM_WOOD);
		DRACORA_PALM_PLANKS = block(EndElemetnModBlocks.DRACORA_PALM_PLANKS);
		DRACORA_PALM_LEAVES = block(EndElemetnModBlocks.DRACORA_PALM_LEAVES);
		DRACORA_PALM_STAIRS = block(EndElemetnModBlocks.DRACORA_PALM_STAIRS);
		DRACORA_PALM_SLAB = block(EndElemetnModBlocks.DRACORA_PALM_SLAB);
		DRACORA_PALM_FENCE = block(EndElemetnModBlocks.DRACORA_PALM_FENCE);
		DRACORA_PALM_FENCE_GATE = block(EndElemetnModBlocks.DRACORA_PALM_FENCE_GATE);
		DRACORA_PALM_PRESSURE_PLATE = block(EndElemetnModBlocks.DRACORA_PALM_PRESSURE_PLATE);
		DRACORA_PALM_BUTTON = block(EndElemetnModBlocks.DRACORA_PALM_BUTTON);
		DRACORA_GRASS = block(EndElemetnModBlocks.DRACORA_GRASS);
		ENDER_JELLYFISH_SPAWN_EGG = REGISTRY.register("ender_jellyfish_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.ENDER_JELLYFISH, -1474561, -7512388, new Item.Properties()));
		VENGEFUL_HEART_OF_ENDER_SPAWN_EGG = REGISTRY.register("vengeful_heart_of_ender_spawn_egg", () -> new DeferredSpawnEggItem(EndElemetnModEntities.VENGEFUL_HEART_OF_ENDER, -15592942, -7208794, new Item.Properties()));
		MOSSY_ENDSTONE_BRICKS = block(EndElemetnModBlocks.MOSSY_ENDSTONE_BRICKS);
		CRACKED_CHORUS_PLANKS = block(EndElemetnModBlocks.CRACKED_CHORUS_PLANKS);
		DIRTY_CHORUS_PLANKS = block(EndElemetnModBlocks.DIRTY_CHORUS_PLANKS);
		CORN_STAGE_0 = block(EndElemetnModBlocks.CORN_STAGE_0);
		CORN_STAGE_1 = doubleBlock(EndElemetnModBlocks.CORN_STAGE_1);
		CORN_STAGE_2 = doubleBlock(EndElemetnModBlocks.CORN_STAGE_2);
		CORN_STAGE_3 = doubleBlock(EndElemetnModBlocks.CORN_STAGE_3);
		CORN_SEEDS = REGISTRY.register("corn_seeds", CornSeedsItem::new);
		CORN = REGISTRY.register("corn", CornItem::new);
		DIMENSIONAL_CUTTER = REGISTRY.register("dimensional_cutter", DimensionalCutterItem::new);
		SHARD_OF_EYE_OF_TELEPORTATION = REGISTRY.register("shard_of_eye_of_teleportation", ShardOfEyeOfTeleportationItem::new);
		HOLE_IN_REALITY = block(EndElemetnModBlocks.HOLE_IN_REALITY);
		END_BOTTLE = REGISTRY.register("end_bottle", EndBottleItem::new);
		FULL_END_BOTTLE = REGISTRY.register("full_end_bottle", FullEndBottleItem::new);
		UNSTABLE_HOLE_IN_REALITY = block(EndElemetnModBlocks.UNSTABLE_HOLE_IN_REALITY);
		EYE_OF_TELEPORTATION = REGISTRY.register("eye_of_teleportation", EyeOfTeleportationItem::new);
		ENDSTONE_KEY = REGISTRY.register("endstone_key", EndstoneKeyItem::new);
		END_SOULFUL_KEY = REGISTRY.register("end_soulful_key", EndSoulfulKeyItem::new);
		WOODEN_HAMMER = REGISTRY.register("wooden_hammer", WoodenHammerItem::new);
		STONE_HAMMER = REGISTRY.register("stone_hammer", StoneHammerItem::new);
		IRON_HAMMER = REGISTRY.register("iron_hammer", IronHammerItem::new);
		GOLDEN_HAMMER = REGISTRY.register("golden_hammer", GoldenHammerItem::new);
		DIAMOND_HAMMER = REGISTRY.register("diamond_hammer", DiamondHammerItem::new);
		NETHERITE_HAMMER = REGISTRY.register("netherite_hammer", NetheriteHammerItem::new);
		WOODEN_SCYTH = REGISTRY.register("wooden_scyth", WoodenScythItem::new);
		STONE_SCYTH = REGISTRY.register("stone_scyth", StoneScythItem::new);
		IRON_SCYTH = REGISTRY.register("iron_scyth", IronScythItem::new);
		GOLDEN_SCYTH = REGISTRY.register("golden_scyth", GoldenScythItem::new);
		DIAMOND_SCYTH = REGISTRY.register("diamond_scyth", DiamondScythItem::new);
		NETHERITE_SCYTH = REGISTRY.register("netherite_scyth", NetheriteScythItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), END_MUD_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), VOID_LIQUID_BUCKET.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}
}