/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.end_elemetn.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.end_elemetn.item.*;
import net.mcreator.end_elemetn.EndElemetnMod;

public class EndElemetnModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, EndElemetnMod.MODID);
	public static final RegistryObject<Item> SHULKER_HELMET = REGISTRY.register("shulker_helmet", () -> new ShulkerItem.Helmet());
	public static final RegistryObject<Item> SHULKER_CHESTPLATE = REGISTRY.register("shulker_chestplate", () -> new ShulkerItem.Chestplate());
	public static final RegistryObject<Item> SHULKER_LEGGINGS = REGISTRY.register("shulker_leggings", () -> new ShulkerItem.Leggings());
	public static final RegistryObject<Item> SHULKER_BOOTS = REGISTRY.register("shulker_boots", () -> new ShulkerItem.Boots());
	public static final RegistryObject<Item> END_COBBELSTONE = block(EndElemetnModBlocks.END_COBBELSTONE);
	public static final RegistryObject<Item> END_MESHFADES_STONE = block(EndElemetnModBlocks.END_MESHFADES_STONE);
	public static final RegistryObject<Item> GREEN_END_STONE = block(EndElemetnModBlocks.GREEN_END_STONE);
	public static final RegistryObject<Item> GREEN_END_COBBLESTONE = block(EndElemetnModBlocks.GREEN_END_COBBLESTONE);
	public static final RegistryObject<Item> DIRTY_END_COBBLESTONE = block(EndElemetnModBlocks.DIRTY_END_COBBLESTONE);
	public static final RegistryObject<Item> CRACKED_GREEN_ENDCOBBLESTONE = block(EndElemetnModBlocks.CRACKED_GREEN_ENDCOBBLESTONE);
	public static final RegistryObject<Item> ENDWILD_GRASS = block(EndElemetnModBlocks.ENDWILD_GRASS);
	public static final RegistryObject<Item> ENDER_WOOD = block(EndElemetnModBlocks.ENDER_WOOD);
	public static final RegistryObject<Item> ENDER_LOG = block(EndElemetnModBlocks.ENDER_LOG);
	public static final RegistryObject<Item> ENDER_PLANKS = block(EndElemetnModBlocks.ENDER_PLANKS);
	public static final RegistryObject<Item> ENDER_LEAVES = block(EndElemetnModBlocks.ENDER_LEAVES);
	public static final RegistryObject<Item> ENDER_STAIRS = block(EndElemetnModBlocks.ENDER_STAIRS);
	public static final RegistryObject<Item> ENDER_SLAB = block(EndElemetnModBlocks.ENDER_SLAB);
	public static final RegistryObject<Item> ENDER_FENCE = block(EndElemetnModBlocks.ENDER_FENCE);
	public static final RegistryObject<Item> ENDER_FENCE_GATE = block(EndElemetnModBlocks.ENDER_FENCE_GATE);
	public static final RegistryObject<Item> ENDER_PRESSURE_PLATE = block(EndElemetnModBlocks.ENDER_PRESSURE_PLATE);
	public static final RegistryObject<Item> ENDER_BUTTON = block(EndElemetnModBlocks.ENDER_BUTTON);
	public static final RegistryObject<Item> END_FERN = doubleBlock(EndElemetnModBlocks.END_FERN);
	public static final RegistryObject<Item> END_TALL_GRESS = doubleBlock(EndElemetnModBlocks.END_TALL_GRESS);
	public static final RegistryObject<Item> END_GRASS = block(EndElemetnModBlocks.END_GRASS);
	public static final RegistryObject<Item> END_WILD_CORAL = block(EndElemetnModBlocks.END_WILD_CORAL);
	public static final RegistryObject<Item> ENDSTONE_GRASS = block(EndElemetnModBlocks.ENDSTONE_GRASS);
	public static final RegistryObject<Item> ENDSTONE_BLOSSOM_GRASS = block(EndElemetnModBlocks.ENDSTONE_BLOSSOM_GRASS);
	public static final RegistryObject<Item> END_VINES = block(EndElemetnModBlocks.END_VINES);
	public static final RegistryObject<Item> END_MUD_BLOCK = block(EndElemetnModBlocks.END_MUD_BLOCK);
	public static final RegistryObject<Item> END_MUD_BUCKET = REGISTRY.register("end_mud_bucket", () -> new EndMudItem());
	public static final RegistryObject<Item> END_WILD_TREE_SAPLING = block(EndElemetnModBlocks.END_WILD_TREE_SAPLING);
	public static final RegistryObject<Item> DRY_CHORUS_FLOWER = block(EndElemetnModBlocks.DRY_CHORUS_FLOWER);
	public static final RegistryObject<Item> DRY_CHORUS_PLANT = block(EndElemetnModBlocks.DRY_CHORUS_PLANT);
	public static final RegistryObject<Item> END_MESH_PICK = block(EndElemetnModBlocks.END_MESH_PICK);
	public static final RegistryObject<Item> ENDER_WOOD_STAIRS = block(EndElemetnModBlocks.ENDER_WOOD_STAIRS);
	public static final RegistryObject<Item> MUDDY_ENDCOBBLESTONE = block(EndElemetnModBlocks.MUDDY_ENDCOBBLESTONE);
	public static final RegistryObject<Item> MUG_GASER_BLOCK = block(EndElemetnModBlocks.MUG_GASER_BLOCK);
	public static final RegistryObject<Item> ENDSTONE_DUST = block(EndElemetnModBlocks.ENDSTONE_DUST);
	public static final RegistryObject<Item> ENDER_DOOR = doubleBlock(EndElemetnModBlocks.ENDER_DOOR);
	public static final RegistryObject<Item> ENDER_TRAPDOOR = block(EndElemetnModBlocks.ENDER_TRAPDOOR);
	public static final RegistryObject<Item> END_WILD_FLOWER = block(EndElemetnModBlocks.END_WILD_FLOWER);
	public static final RegistryObject<Item> SNARELINGWEB = block(EndElemetnModBlocks.SNARELINGWEB);
	public static final RegistryObject<Item> SNARELINGBLOB = REGISTRY.register("snarelingblob", () -> new SnarelingblobItem());
	public static final RegistryObject<Item> VOID_LIQUID_BUCKET = REGISTRY.register("void_liquid_bucket", () -> new VoidLiquidItem());
	public static final RegistryObject<Item> VOID_BLOCK = block(EndElemetnModBlocks.VOID_BLOCK);
	public static final RegistryObject<Item> VOID_FLAME = block(EndElemetnModBlocks.VOID_FLAME);
	public static final RegistryObject<Item> WATCHLING_SPAWN_EGG = REGISTRY.register("watchling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.WATCHLING, -15592942, -2809881, new Item.Properties()));
	public static final RegistryObject<Item> SNARELING_SPAWN_EGG = REGISTRY.register("snareling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.SNARELING, -15592942, -5570816, new Item.Properties()));
	public static final RegistryObject<Item> BLASTLING_SPAWN_EGG = REGISTRY.register("blastling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.BLASTLING, -15592942, -364300, new Item.Properties()));
	public static final RegistryObject<Item> LURELING_SPAWN_EGG = REGISTRY.register("lureling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.LURELING, -15592942, -46382, new Item.Properties()));
	public static final RegistryObject<Item> TRUMPLING_SPAWN_EGG = REGISTRY.register("trumpling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.TRUMPLING, -15592942, -14735049, new Item.Properties()));
	public static final RegistryObject<Item> ENDERSENT_SPAWN_EGG = REGISTRY.register("endersent_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.ENDERSENT, -15856114, -15704488, new Item.Properties()));
	public static final RegistryObject<Item> EYED_ENDERSENT_SPAWN_EGG = REGISTRY.register("eyed_endersent_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.EYED_ENDERSENT, -15856114, -15704488, new Item.Properties()));
	public static final RegistryObject<Item> END_WARPED_GRASS = block(EndElemetnModBlocks.END_WARPED_GRASS);
	public static final RegistryObject<Item> WARPED_LOG = block(EndElemetnModBlocks.WARPED_LOG);
	public static final RegistryObject<Item> WARPED_WOOD = block(EndElemetnModBlocks.WARPED_WOOD);
	public static final RegistryObject<Item> WARPED_PLANKS = block(EndElemetnModBlocks.WARPED_PLANKS);
	public static final RegistryObject<Item> WARPED_LEAVES = block(EndElemetnModBlocks.WARPED_LEAVES);
	public static final RegistryObject<Item> WARPED_STAIRS = block(EndElemetnModBlocks.WARPED_STAIRS);
	public static final RegistryObject<Item> WARPED_SLAB = block(EndElemetnModBlocks.WARPED_SLAB);
	public static final RegistryObject<Item> WARPED_FENCE = block(EndElemetnModBlocks.WARPED_FENCE);
	public static final RegistryObject<Item> WARPED_FENCE_GATE = block(EndElemetnModBlocks.WARPED_FENCE_GATE);
	public static final RegistryObject<Item> WARPED_PRESSURE_PLATE = block(EndElemetnModBlocks.WARPED_PRESSURE_PLATE);
	public static final RegistryObject<Item> WARPED_BUTTON = block(EndElemetnModBlocks.WARPED_BUTTON);
	public static final RegistryObject<Item> WARPED_FLOOR_ROOTS = block(EndElemetnModBlocks.WARPED_FLOOR_ROOTS);
	public static final RegistryObject<Item> CHORUS_GRASS = block(EndElemetnModBlocks.CHORUS_GRASS);
	public static final RegistryObject<Item> CHORUS_LOG = block(EndElemetnModBlocks.CHORUS_LOG);
	public static final RegistryObject<Item> CHORUS_WOOD = block(EndElemetnModBlocks.CHORUS_WOOD);
	public static final RegistryObject<Item> CHORUS_PLANKS = block(EndElemetnModBlocks.CHORUS_PLANKS);
	public static final RegistryObject<Item> CHORUS_LEAVES = block(EndElemetnModBlocks.CHORUS_LEAVES);
	public static final RegistryObject<Item> CHORUS_STAIRS = block(EndElemetnModBlocks.CHORUS_STAIRS);
	public static final RegistryObject<Item> CHORUS_SLAB = block(EndElemetnModBlocks.CHORUS_SLAB);
	public static final RegistryObject<Item> CHORUS_FENCE = block(EndElemetnModBlocks.CHORUS_FENCE);
	public static final RegistryObject<Item> CHORUS_FENCE_GATE = block(EndElemetnModBlocks.CHORUS_FENCE_GATE);
	public static final RegistryObject<Item> CHORUS_PRESSURE_PLATE = block(EndElemetnModBlocks.CHORUS_PRESSURE_PLATE);
	public static final RegistryObject<Item> CHORUS_BUTTON = block(EndElemetnModBlocks.CHORUS_BUTTON);
	public static final RegistryObject<Item> CHORUS_VINES = block(EndElemetnModBlocks.CHORUS_VINES);
	public static final RegistryObject<Item> CHORUS_BLOSSOM_GRASS = block(EndElemetnModBlocks.CHORUS_BLOSSOM_GRASS);
	public static final RegistryObject<Item> CHORUS_PLANT = block(EndElemetnModBlocks.CHORUS_PLANT);
	public static final RegistryObject<Item> TALL_CHORUS_PLANT = doubleBlock(EndElemetnModBlocks.TALL_CHORUS_PLANT);
	public static final RegistryObject<Item> CHORUS_SHROOM = block(EndElemetnModBlocks.CHORUS_SHROOM);
	public static final RegistryObject<Item> TALL_CHORUS_BLOSSOM_GRASS = doubleBlock(EndElemetnModBlocks.TALL_CHORUS_BLOSSOM_GRASS);
	public static final RegistryObject<Item> ENDERITE_ORE = block(EndElemetnModBlocks.ENDERITE_ORE);
	public static final RegistryObject<Item> TITANIUM_ORE = block(EndElemetnModBlocks.TITANIUM_ORE);
	public static final RegistryObject<Item> ENDERITE = REGISTRY.register("enderite", () -> new EnderiteItem());
	public static final RegistryObject<Item> RAW_TITANIUM = REGISTRY.register("raw_titanium", () -> new RawTitaniumItem());
	public static final RegistryObject<Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", () -> new TitaniumIngotItem());
	public static final RegistryObject<Item> TITANIUM_NUGGET = REGISTRY.register("titanium_nugget", () -> new TitaniumNuggetItem());
	public static final RegistryObject<Item> TITANIUM_COIN = REGISTRY.register("titanium_coin", () -> new TitaniumCoinItem());
	public static final RegistryObject<Item> COMMPREST_VOID = block(EndElemetnModBlocks.COMMPREST_VOID);
	public static final RegistryObject<Item> CRACKED_ENDSTONE_BRICKS = block(EndElemetnModBlocks.CRACKED_ENDSTONE_BRICKS);
	public static final RegistryObject<Item> CHISELED_ENDSTONE_BRICKS = block(EndElemetnModBlocks.CHISELED_ENDSTONE_BRICKS);
	public static final RegistryObject<Item> ENDSTONE_TILES = block(EndElemetnModBlocks.ENDSTONE_TILES);
	public static final RegistryObject<Item> POLISHED_ENDSTONE = block(EndElemetnModBlocks.POLISHED_ENDSTONE);
	public static final RegistryObject<Item> ENDSTONE_PILLAR = block(EndElemetnModBlocks.ENDSTONE_PILLAR);
	public static final RegistryObject<Item> ARCH_ENDSTONE_PILLAR = block(EndElemetnModBlocks.ARCH_ENDSTONE_PILLAR);
	public static final RegistryObject<Item> SMOOTH_PURPUR = block(EndElemetnModBlocks.SMOOTH_PURPUR);
	public static final RegistryObject<Item> CRACKED_PURPUR = block(EndElemetnModBlocks.CRACKED_PURPUR);
	public static final RegistryObject<Item> PURPUR_TILES = block(EndElemetnModBlocks.PURPUR_TILES);
	public static final RegistryObject<Item> CUBET_PURPUR_TILES = block(EndElemetnModBlocks.CUBET_PURPUR_TILES);
	public static final RegistryObject<Item> CHISELED_PURPUR = block(EndElemetnModBlocks.CHISELED_PURPUR);
	public static final RegistryObject<Item> CRYSTALLIZED_PURPUR = REGISTRY.register("crystallized_purpur", () -> new CrystallizedPurpurItem());
	public static final RegistryObject<Item> TRADLING_SPAWN_EGG = REGISTRY.register("tradling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.TRADLING, -15395563, -5289500, new Item.Properties()));
	public static final RegistryObject<Item> ENDERBABY_SPAWN_EGG = REGISTRY.register("enderbaby_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.ENDERBABY, -15921907, -29975, new Item.Properties()));
	public static final RegistryObject<Item> ENDSTONE_LOOTBOX = REGISTRY.register("endstone_lootbox", () -> new EndstoneLootboxItem());
	public static final RegistryObject<Item> TITANIUM_LOOTBOX = REGISTRY.register("titanium_lootbox", () -> new TitaniumLootboxItem());
	public static final RegistryObject<Item> ENDERITE_LOOTBOX = REGISTRY.register("enderite_lootbox", () -> new EnderiteLootboxItem());
	public static final RegistryObject<Item> WEAPON_SMITHING_TEMPLATE = REGISTRY.register("weapon_smithing_template", () -> new WeaponSmeathingTemplateItem());
	public static final RegistryObject<Item> SHULKER_UPGRADER_SMITHING_TEMPLATE = REGISTRY.register("shulker_upgrader_smithing_template", () -> new ShulkerUpgraderSmithingTemplateItem());
	public static final RegistryObject<Item> ENTERNAL_UPGRADER_SMITHING_TEMPLATE = REGISTRY.register("enternal_upgrader_smithing_template", () -> new EnternalUpgraderSmithingTemplateItem());
	public static final RegistryObject<Item> PURPUR_WALL = block(EndElemetnModBlocks.PURPUR_WALL);
	public static final RegistryObject<Item> END_CITY_VAULT = block(EndElemetnModBlocks.END_CITY_VAULT);
	public static final RegistryObject<Item> END_CITY_KEY = REGISTRY.register("end_city_key", () -> new EndCityKeyItem());
	public static final RegistryObject<Item> ENDERITE_HELMET = REGISTRY.register("enderite_helmet", () -> new EnternalItem.Helmet());
	public static final RegistryObject<Item> ENDERITE_CHESTPLATE = REGISTRY.register("enderite_chestplate", () -> new EnternalItem.Chestplate());
	public static final RegistryObject<Item> ENDERITE_LEGGINGS = REGISTRY.register("enderite_leggings", () -> new EnternalItem.Leggings());
	public static final RegistryObject<Item> ENDERITE_BOOTS = REGISTRY.register("enderite_boots", () -> new EnternalItem.Boots());
	public static final RegistryObject<Item> ENDERITHE_SHOVEL = REGISTRY.register("enderithe_shovel", () -> new EnternalShovelItem());
	public static final RegistryObject<Item> ENDERITHE_SWORD = REGISTRY.register("enderithe_sword", () -> new EnternalSwordItem());
	public static final RegistryObject<Item> ENDERITHE_PICKAXE = REGISTRY.register("enderithe_pickaxe", () -> new EnternalPickaxeItem());
	public static final RegistryObject<Item> ENDERITHE_AXE = REGISTRY.register("enderithe_axe", () -> new EnternalAxeItem());
	public static final RegistryObject<Item> ENDERITHE_HOE = REGISTRY.register("enderithe_hoe", () -> new EnternalHoeItem());
	public static final RegistryObject<Item> ENDERITHE_SCYTHE = REGISTRY.register("enderithe_scythe", () -> new EnternalScytheItem());
	public static final RegistryObject<Item> ENDERITHE_BOW = REGISTRY.register("enderithe_bow", () -> new EnternalBowItem());
	public static final RegistryObject<Item> ENDERITHE_PICKAXE_SHARD = REGISTRY.register("enderithe_pickaxe_shard", () -> new EnternalPickaxeShardItem());
	public static final RegistryObject<Item> ENDERITHE_AXE_SHARD = REGISTRY.register("enderithe_axe_shard", () -> new EnternalAxeShardItem());
	public static final RegistryObject<Item> ENDERITHE_HOE_SHARD = REGISTRY.register("enderithe_hoe_shard", () -> new EnternalHoeShardItem());
	public static final RegistryObject<Item> ENDERITHE_SWORD_SHARD = REGISTRY.register("enderithe_sword_shard", () -> new EnternalSwordShardItem());
	public static final RegistryObject<Item> ENDERITHE_SHOWEL_SHARD = REGISTRY.register("enderithe_showel_shard", () -> new EnternalShowelShardItem());
	public static final RegistryObject<Item> ENDERITHE_BOW_SHARD = REGISTRY.register("enderithe_bow_shard", () -> new EnternalBowShardItem());
	public static final RegistryObject<Item> ENDERITHE_SCYTHE_SHARD = REGISTRY.register("enderithe_scythe_shard", () -> new EnternalScytheShardItem());
	public static final RegistryObject<Item> ENDERITHE_HAMMER = REGISTRY.register("enderithe_hammer", () -> new EnternalHammerItem());
	public static final RegistryObject<Item> ENDERITHE_HAMMER_SHARD = REGISTRY.register("enderithe_hammer_shard", () -> new EnternalHammerShardItem());
	public static final RegistryObject<Item> END_SPAWNER = block(EndElemetnModBlocks.END_SPAWNER);
	public static final RegistryObject<Item> END_FIRE = block(EndElemetnModBlocks.END_FIRE);
	public static final RegistryObject<Item> METEOR_SCRAP = REGISTRY.register("meteor_scrap", () -> new ChorusScrapItem());
	public static final RegistryObject<Item> UPGRADED_ENDERITHE_INGOT = REGISTRY.register("upgraded_enderithe_ingot", () -> new UpgradedEnternalShardItem());
	public static final RegistryObject<Item> ENDERITHE_INGOT = REGISTRY.register("enderithe_ingot", () -> new EnternalShardItem());
	public static final RegistryObject<Item> METEOR_DEBRIS = block(EndElemetnModBlocks.METEOR_DEBRIS);
	public static final RegistryObject<Item> CELESTIAN_GUARD_SPAWN_EGG = REGISTRY.register("celestian_guard_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.CELESTIAN_GUARD, -9743246, -9476750, new Item.Properties()));
	public static final RegistryObject<Item> TITANIUM_PEDESTAL = block(EndElemetnModBlocks.TITANIUM_PEDESTAL);
	public static final RegistryObject<Item> STAR = REGISTRY.register("star", () -> new StarItem());
	public static final RegistryObject<Item> TITANIUM_BLOCK = block(EndElemetnModBlocks.TITANIUM_BLOCK);
	public static final RegistryObject<Item> SHADOWLING_SPAWN_EGG = REGISTRY.register("shadowling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.SHADOWLING, -16121826, -16711670, new Item.Properties()));
	public static final RegistryObject<Item> SHADOW_GRASS = block(EndElemetnModBlocks.SHADOW_GRASS);
	public static final RegistryObject<Item> PILLARS_OF_SHADOW_WOOD = block(EndElemetnModBlocks.PILLARS_OF_SHADOW_WOOD);
	public static final RegistryObject<Item> UNKNOWN_BLOCK = block(EndElemetnModBlocks.UNKNOWN_BLOCK);
	public static final RegistryObject<Item> ENTERNAL_RAW_ORE = REGISTRY.register("enternal_raw_ore", () -> new EnternalRawOreItem());
	public static final RegistryObject<Item> NECROSENT_SPAWN_EGG = REGISTRY.register("necrosent_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.NECROSENT, -16250871, -9769729, new Item.Properties()));
	public static final RegistryObject<Item> CRYING_WATCHLING_SPAWN_EGG = REGISTRY.register("crying_watchling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.CRYING_WATCHLING, -15592942, -14695961, new Item.Properties()));
	public static final RegistryObject<Item> CRYING_SNARELING_SPAWN_EGG = REGISTRY.register("crying_snareling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.CRYING_SNARELING, -15592942, -16711713, new Item.Properties()));
	public static final RegistryObject<Item> CRYING_BLASTLING_SPAWN_EGG = REGISTRY.register("crying_blastling_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.CRYING_BLASTLING, -15592942, -9376262, new Item.Properties()));
	public static final RegistryObject<Item> THE_END_SHARD = REGISTRY.register("the_end_shard", () -> new TheEndShardItem());
	public static final RegistryObject<Item> BLASTLING_SHOOT = REGISTRY.register("blastling_shoot", () -> new BlastlingShootItem());
	public static final RegistryObject<Item> LURE = REGISTRY.register("lure", () -> new LureItem());
	public static final RegistryObject<Item> WATCHLING_EYE = REGISTRY.register("watchling_eye", () -> new WatchlingEyeItem());
	public static final RegistryObject<Item> THUMPET = REGISTRY.register("thumpet", () -> new ThumpetItem());
	public static final RegistryObject<Item> FUSELING = REGISTRY.register("fuseling", () -> new FuselingItem());
	public static final RegistryObject<Item> SNARE_STRING = REGISTRY.register("snare_string", () -> new SnareStringItem());
	public static final RegistryObject<Item> CORRUPTED_BEACON = REGISTRY.register("corrupted_beacon", () -> new CorruptedBeaconItem());
	public static final RegistryObject<Item> DRAGON_FRUIT_GROW = block(EndElemetnModBlocks.DRAGON_FRUIT_GROW);
	public static final RegistryObject<Item> DRAGON_FRUIT = REGISTRY.register("dragon_fruit", () -> new DragonFruitItem());
	public static final RegistryObject<Item> DRACORA_PALM_LOG = block(EndElemetnModBlocks.DRACORA_PALM_LOG);
	public static final RegistryObject<Item> DRACORA_PALM_WOOD = block(EndElemetnModBlocks.DRACORA_PALM_WOOD);
	public static final RegistryObject<Item> DRACORA_PALM_PLANKS = block(EndElemetnModBlocks.DRACORA_PALM_PLANKS);
	public static final RegistryObject<Item> DRACORA_PALM_LEAVES = block(EndElemetnModBlocks.DRACORA_PALM_LEAVES);
	public static final RegistryObject<Item> DRACORA_PALM_STAIRS = block(EndElemetnModBlocks.DRACORA_PALM_STAIRS);
	public static final RegistryObject<Item> DRACORA_PALM_SLAB = block(EndElemetnModBlocks.DRACORA_PALM_SLAB);
	public static final RegistryObject<Item> DRACORA_PALM_FENCE = block(EndElemetnModBlocks.DRACORA_PALM_FENCE);
	public static final RegistryObject<Item> DRACORA_PALM_FENCE_GATE = block(EndElemetnModBlocks.DRACORA_PALM_FENCE_GATE);
	public static final RegistryObject<Item> DRACORA_PALM_PRESSURE_PLATE = block(EndElemetnModBlocks.DRACORA_PALM_PRESSURE_PLATE);
	public static final RegistryObject<Item> DRACORA_PALM_BUTTON = block(EndElemetnModBlocks.DRACORA_PALM_BUTTON);
	public static final RegistryObject<Item> DRACORA_GRASS = block(EndElemetnModBlocks.DRACORA_GRASS);
	public static final RegistryObject<Item> ENDER_JELLYFISH_SPAWN_EGG = REGISTRY.register("ender_jellyfish_spawn_egg", () -> new ForgeSpawnEggItem(EndElemetnModEntities.ENDER_JELLYFISH, -1474561, -7512388, new Item.Properties()));
	public static final RegistryObject<Item> VENGEFUL_HEART_OF_ENDER_SPAWN_EGG = REGISTRY.register("vengeful_heart_of_ender_spawn_egg",
			() -> new ForgeSpawnEggItem(EndElemetnModEntities.VENGEFUL_HEART_OF_ENDER, -15592942, -7208794, new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_ENDSTONE_BRICKS = block(EndElemetnModBlocks.MOSSY_ENDSTONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_CHORUS_PLANKS = block(EndElemetnModBlocks.CRACKED_CHORUS_PLANKS);
	public static final RegistryObject<Item> DIRTY_CHORUS_PLANKS = block(EndElemetnModBlocks.DIRTY_CHORUS_PLANKS);
	public static final RegistryObject<Item> CORN_STAGE_0 = block(EndElemetnModBlocks.CORN_STAGE_0);
	public static final RegistryObject<Item> CORN_STAGE_1 = doubleBlock(EndElemetnModBlocks.CORN_STAGE_1);
	public static final RegistryObject<Item> CORN_STAGE_2 = doubleBlock(EndElemetnModBlocks.CORN_STAGE_2);
	public static final RegistryObject<Item> CORN_STAGE_3 = doubleBlock(EndElemetnModBlocks.CORN_STAGE_3);
	public static final RegistryObject<Item> CORN_SEEDS = REGISTRY.register("corn_seeds", () -> new CornSeedsItem());
	public static final RegistryObject<Item> CORN = REGISTRY.register("corn", () -> new CornItem());
	public static final RegistryObject<Item> DIMENSIONAL_CUTTER = REGISTRY.register("dimensional_cutter", () -> new DimensionalCutterItem());
	public static final RegistryObject<Item> SHARD_OF_EYE_OF_TELEPORTATION = REGISTRY.register("shard_of_eye_of_teleportation", () -> new ShardOfEyeOfTeleportationItem());
	public static final RegistryObject<Item> HOLE_IN_REALITY = block(EndElemetnModBlocks.HOLE_IN_REALITY);
	public static final RegistryObject<Item> END_BOTTLE = REGISTRY.register("end_bottle", () -> new EndBottleItem());
	public static final RegistryObject<Item> FULL_END_BOTTLE = REGISTRY.register("full_end_bottle", () -> new FullEndBottleItem());
	public static final RegistryObject<Item> UNSTABLE_HOLE_IN_REALITY = block(EndElemetnModBlocks.UNSTABLE_HOLE_IN_REALITY);
	public static final RegistryObject<Item> EYE_OF_TELEPORTATION = REGISTRY.register("eye_of_teleportation", () -> new EyeOfTeleportationItem());
	public static final RegistryObject<Item> ENDSTONE_KEY = REGISTRY.register("endstone_key", () -> new EndstoneKeyItem());
	public static final RegistryObject<Item> END_SOULFUL_KEY = REGISTRY.register("end_soulful_key", () -> new EndSoulfulKeyItem());
	public static final RegistryObject<Item> WOODEN_HAMMER = REGISTRY.register("wooden_hammer", () -> new WoodenHammerItem());
	public static final RegistryObject<Item> STONE_HAMMER = REGISTRY.register("stone_hammer", () -> new StoneHammerItem());
	public static final RegistryObject<Item> IRON_HAMMER = REGISTRY.register("iron_hammer", () -> new IronHammerItem());
	public static final RegistryObject<Item> GOLDEN_HAMMER = REGISTRY.register("golden_hammer", () -> new GoldenHammerItem());
	public static final RegistryObject<Item> DIAMOND_HAMMER = REGISTRY.register("diamond_hammer", () -> new DiamondHammerItem());
	public static final RegistryObject<Item> NETHERITE_HAMMER = REGISTRY.register("netherite_hammer", () -> new NetheriteHammerItem());
	public static final RegistryObject<Item> WOODEN_SCYTH = REGISTRY.register("wooden_scyth", () -> new WoodenScythItem());
	public static final RegistryObject<Item> STONE_SCYTH = REGISTRY.register("stone_scyth", () -> new StoneScythItem());
	public static final RegistryObject<Item> IRON_SCYTH = REGISTRY.register("iron_scyth", () -> new IronScythItem());
	public static final RegistryObject<Item> GOLDEN_SCYTH = REGISTRY.register("golden_scyth", () -> new GoldenScythItem());
	public static final RegistryObject<Item> DIAMOND_SCYTH = REGISTRY.register("diamond_scyth", () -> new DiamondScythItem());
	public static final RegistryObject<Item> NETHERITE_SCYTH = REGISTRY.register("netherite_scyth", () -> new NetheriteScythItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}