/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.end_elemetn.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.end_elemetn.block.*;
import net.mcreator.end_elemetn.EndElemetnMod;

public class EndElemetnModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(EndElemetnMod.MODID);
	public static final DeferredBlock<Block> END_COBBELSTONE;
	public static final DeferredBlock<Block> END_MESHFADES_STONE;
	public static final DeferredBlock<Block> GREEN_END_STONE;
	public static final DeferredBlock<Block> GREEN_END_COBBLESTONE;
	public static final DeferredBlock<Block> DIRTY_END_COBBLESTONE;
	public static final DeferredBlock<Block> CRACKED_GREEN_ENDCOBBLESTONE;
	public static final DeferredBlock<Block> ENDWILD_GRASS;
	public static final DeferredBlock<Block> ENDER_WOOD;
	public static final DeferredBlock<Block> ENDER_LOG;
	public static final DeferredBlock<Block> ENDER_PLANKS;
	public static final DeferredBlock<Block> ENDER_LEAVES;
	public static final DeferredBlock<Block> ENDER_STAIRS;
	public static final DeferredBlock<Block> ENDER_SLAB;
	public static final DeferredBlock<Block> ENDER_FENCE;
	public static final DeferredBlock<Block> ENDER_FENCE_GATE;
	public static final DeferredBlock<Block> ENDER_PRESSURE_PLATE;
	public static final DeferredBlock<Block> ENDER_BUTTON;
	public static final DeferredBlock<Block> END_FERN;
	public static final DeferredBlock<Block> END_TALL_GRESS;
	public static final DeferredBlock<Block> END_GRASS;
	public static final DeferredBlock<Block> END_WILD_CORAL;
	public static final DeferredBlock<Block> ENDSTONE_GRASS;
	public static final DeferredBlock<Block> ENDSTONE_BLOSSOM_GRASS;
	public static final DeferredBlock<Block> END_VINES;
	public static final DeferredBlock<Block> END_MUD_BLOCK;
	public static final DeferredBlock<Block> END_MUD;
	public static final DeferredBlock<Block> END_WILD_TREE_SAPLING;
	public static final DeferredBlock<Block> DRY_CHORUS_FLOWER;
	public static final DeferredBlock<Block> DRY_CHORUS_PLANT;
	public static final DeferredBlock<Block> END_MESH_PICK;
	public static final DeferredBlock<Block> ENDER_WOOD_STAIRS;
	public static final DeferredBlock<Block> MUDDY_ENDCOBBLESTONE;
	public static final DeferredBlock<Block> MUG_GASER_BLOCK;
	public static final DeferredBlock<Block> ENDSTONE_DUST;
	public static final DeferredBlock<Block> ENDER_DOOR;
	public static final DeferredBlock<Block> ENDER_TRAPDOOR;
	public static final DeferredBlock<Block> END_WILD_FLOWER;
	public static final DeferredBlock<Block> SNARELINGWEB;
	public static final DeferredBlock<Block> VOID_LIQUID;
	public static final DeferredBlock<Block> VOID_BLOCK;
	public static final DeferredBlock<Block> VOID_FLAME;
	public static final DeferredBlock<Block> END_WARPED_GRASS;
	public static final DeferredBlock<Block> WARPED_LOG;
	public static final DeferredBlock<Block> WARPED_WOOD;
	public static final DeferredBlock<Block> WARPED_PLANKS;
	public static final DeferredBlock<Block> WARPED_LEAVES;
	public static final DeferredBlock<Block> WARPED_STAIRS;
	public static final DeferredBlock<Block> WARPED_SLAB;
	public static final DeferredBlock<Block> WARPED_FENCE;
	public static final DeferredBlock<Block> WARPED_FENCE_GATE;
	public static final DeferredBlock<Block> WARPED_PRESSURE_PLATE;
	public static final DeferredBlock<Block> WARPED_BUTTON;
	public static final DeferredBlock<Block> WARPED_FLOOR_ROOTS;
	public static final DeferredBlock<Block> CHORUS_GRASS;
	public static final DeferredBlock<Block> CHORUS_LOG;
	public static final DeferredBlock<Block> CHORUS_WOOD;
	public static final DeferredBlock<Block> CHORUS_PLANKS;
	public static final DeferredBlock<Block> CHORUS_LEAVES;
	public static final DeferredBlock<Block> CHORUS_STAIRS;
	public static final DeferredBlock<Block> CHORUS_SLAB;
	public static final DeferredBlock<Block> CHORUS_FENCE;
	public static final DeferredBlock<Block> CHORUS_FENCE_GATE;
	public static final DeferredBlock<Block> CHORUS_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CHORUS_BUTTON;
	public static final DeferredBlock<Block> CHORUS_VINES;
	public static final DeferredBlock<Block> CHORUS_BLOSSOM_GRASS;
	public static final DeferredBlock<Block> CHORUS_PLANT;
	public static final DeferredBlock<Block> TALL_CHORUS_PLANT;
	public static final DeferredBlock<Block> CHORUS_SHROOM;
	public static final DeferredBlock<Block> TALL_CHORUS_BLOSSOM_GRASS;
	public static final DeferredBlock<Block> ENDERITE_ORE;
	public static final DeferredBlock<Block> TITANIUM_ORE;
	public static final DeferredBlock<Block> COMMPREST_VOID;
	public static final DeferredBlock<Block> CRACKED_ENDSTONE_BRICKS;
	public static final DeferredBlock<Block> CHISELED_ENDSTONE_BRICKS;
	public static final DeferredBlock<Block> ENDSTONE_TILES;
	public static final DeferredBlock<Block> POLISHED_ENDSTONE;
	public static final DeferredBlock<Block> ENDSTONE_PILLAR;
	public static final DeferredBlock<Block> ARCH_ENDSTONE_PILLAR;
	public static final DeferredBlock<Block> SMOOTH_PURPUR;
	public static final DeferredBlock<Block> CRACKED_PURPUR;
	public static final DeferredBlock<Block> PURPUR_TILES;
	public static final DeferredBlock<Block> CUBET_PURPUR_TILES;
	public static final DeferredBlock<Block> CHISELED_PURPUR;
	public static final DeferredBlock<Block> PURPUR_WALL;
	public static final DeferredBlock<Block> END_CITY_VAULT;
	public static final DeferredBlock<Block> END_SPAWNER;
	public static final DeferredBlock<Block> END_FIRE;
	public static final DeferredBlock<Block> METEOR_DEBRIS;
	public static final DeferredBlock<Block> TITANIUM_PEDESTAL;
	public static final DeferredBlock<Block> TITANIUM_BLOCK;
	public static final DeferredBlock<Block> SHADOW_GRASS;
	public static final DeferredBlock<Block> PILLARS_OF_SHADOW_WOOD;
	public static final DeferredBlock<Block> UNKNOWN_BLOCK;
	public static final DeferredBlock<Block> DRAGON_FRUIT_GROW;
	public static final DeferredBlock<Block> DRACORA_PALM_LOG;
	public static final DeferredBlock<Block> DRACORA_PALM_WOOD;
	public static final DeferredBlock<Block> DRACORA_PALM_PLANKS;
	public static final DeferredBlock<Block> DRACORA_PALM_LEAVES;
	public static final DeferredBlock<Block> DRACORA_PALM_STAIRS;
	public static final DeferredBlock<Block> DRACORA_PALM_SLAB;
	public static final DeferredBlock<Block> DRACORA_PALM_FENCE;
	public static final DeferredBlock<Block> DRACORA_PALM_FENCE_GATE;
	public static final DeferredBlock<Block> DRACORA_PALM_PRESSURE_PLATE;
	public static final DeferredBlock<Block> DRACORA_PALM_BUTTON;
	public static final DeferredBlock<Block> DRACORA_GRASS;
	public static final DeferredBlock<Block> MOSSY_ENDSTONE_BRICKS;
	public static final DeferredBlock<Block> CRACKED_CHORUS_PLANKS;
	public static final DeferredBlock<Block> DIRTY_CHORUS_PLANKS;
	public static final DeferredBlock<Block> CORN_STAGE_0;
	public static final DeferredBlock<Block> CORN_STAGE_1;
	public static final DeferredBlock<Block> CORN_STAGE_2;
	public static final DeferredBlock<Block> CORN_STAGE_3;
	public static final DeferredBlock<Block> HOLE_IN_REALITY;
	public static final DeferredBlock<Block> UNSTABLE_HOLE_IN_REALITY;
	static {
		END_COBBELSTONE = REGISTRY.register("end_cobbelstone", EndCobbelstoneBlock::new);
		END_MESHFADES_STONE = REGISTRY.register("end_meshfades_stone", EndMeshfadesStoneBlock::new);
		GREEN_END_STONE = REGISTRY.register("green_end_stone", GreenEndStoneBlock::new);
		GREEN_END_COBBLESTONE = REGISTRY.register("green_end_cobblestone", GreenEndCobblestoneBlock::new);
		DIRTY_END_COBBLESTONE = REGISTRY.register("dirty_end_cobblestone", DirtyEndCobblestoneBlock::new);
		CRACKED_GREEN_ENDCOBBLESTONE = REGISTRY.register("cracked_green_endcobblestone", CrackedGreenEndcobblestoneBlock::new);
		ENDWILD_GRASS = REGISTRY.register("endwild_grass", EndwildGrassBlock::new);
		ENDER_WOOD = REGISTRY.register("ender_wood", EnderWoodBlock::new);
		ENDER_LOG = REGISTRY.register("ender_log", EnderLogBlock::new);
		ENDER_PLANKS = REGISTRY.register("ender_planks", EnderPlanksBlock::new);
		ENDER_LEAVES = REGISTRY.register("ender_leaves", EnderLeavesBlock::new);
		ENDER_STAIRS = REGISTRY.register("ender_stairs", EnderStairsBlock::new);
		ENDER_SLAB = REGISTRY.register("ender_slab", EnderSlabBlock::new);
		ENDER_FENCE = REGISTRY.register("ender_fence", EnderFenceBlock::new);
		ENDER_FENCE_GATE = REGISTRY.register("ender_fence_gate", EnderFenceGateBlock::new);
		ENDER_PRESSURE_PLATE = REGISTRY.register("ender_pressure_plate", EnderPressurePlateBlock::new);
		ENDER_BUTTON = REGISTRY.register("ender_button", EnderButtonBlock::new);
		END_FERN = REGISTRY.register("end_fern", EndFernBlock::new);
		END_TALL_GRESS = REGISTRY.register("end_tall_gress", EndTallGressBlock::new);
		END_GRASS = REGISTRY.register("end_grass", EndGrassBlock::new);
		END_WILD_CORAL = REGISTRY.register("end_wild_coral", EndWildCoralBlock::new);
		ENDSTONE_GRASS = REGISTRY.register("endstone_grass", EndstoneGrassBlock::new);
		ENDSTONE_BLOSSOM_GRASS = REGISTRY.register("endstone_blossom_grass", EndstoneBlossomGrassBlock::new);
		END_VINES = REGISTRY.register("end_vines", EndVinesBlock::new);
		END_MUD_BLOCK = REGISTRY.register("end_mud_block", EndMudBlockBlock::new);
		END_MUD = REGISTRY.register("end_mud", EndMudBlock::new);
		END_WILD_TREE_SAPLING = REGISTRY.register("end_wild_tree_sapling", EndWildTreeSaplingBlock::new);
		DRY_CHORUS_FLOWER = REGISTRY.register("dry_chorus_flower", DryChorusBlock::new);
		DRY_CHORUS_PLANT = REGISTRY.register("dry_chorus_plant", DryChorusPlantBlock::new);
		END_MESH_PICK = REGISTRY.register("end_mesh_pick", EndMeshPickBlock::new);
		ENDER_WOOD_STAIRS = REGISTRY.register("ender_wood_stairs", EnderWoodStairsBlock::new);
		MUDDY_ENDCOBBLESTONE = REGISTRY.register("muddy_endcobblestone", MuddyEndcobblestoneBlock::new);
		MUG_GASER_BLOCK = REGISTRY.register("mug_gaser_block", MugGaserBlockBlock::new);
		ENDSTONE_DUST = REGISTRY.register("endstone_dust", EndstoneDustBlock::new);
		ENDER_DOOR = REGISTRY.register("ender_door", EnderDoorBlock::new);
		ENDER_TRAPDOOR = REGISTRY.register("ender_trapdoor", EnderTrapdoorBlock::new);
		END_WILD_FLOWER = REGISTRY.register("end_wild_flower", EndWildFlowerBlock::new);
		SNARELINGWEB = REGISTRY.register("snarelingweb", SnarelingwebBlock::new);
		VOID_LIQUID = REGISTRY.register("void_liquid", VoidLiquidBlock::new);
		VOID_BLOCK = REGISTRY.register("void_block", VoidBlockBlock::new);
		VOID_FLAME = REGISTRY.register("void_flame", VoidFlameBlock::new);
		END_WARPED_GRASS = REGISTRY.register("end_warped_grass", EndWarpedGrassBlock::new);
		WARPED_LOG = REGISTRY.register("warped_log", WarpedLogBlock::new);
		WARPED_WOOD = REGISTRY.register("warped_wood", WarpedWoodBlock::new);
		WARPED_PLANKS = REGISTRY.register("warped_planks", WarpedPlanksBlock::new);
		WARPED_LEAVES = REGISTRY.register("warped_leaves", WarpedLeavesBlock::new);
		WARPED_STAIRS = REGISTRY.register("warped_stairs", WarpedStairsBlock::new);
		WARPED_SLAB = REGISTRY.register("warped_slab", WarpedSlabBlock::new);
		WARPED_FENCE = REGISTRY.register("warped_fence", WarpedFenceBlock::new);
		WARPED_FENCE_GATE = REGISTRY.register("warped_fence_gate", WarpedFenceGateBlock::new);
		WARPED_PRESSURE_PLATE = REGISTRY.register("warped_pressure_plate", WarpedPressurePlateBlock::new);
		WARPED_BUTTON = REGISTRY.register("warped_button", WarpedButtonBlock::new);
		WARPED_FLOOR_ROOTS = REGISTRY.register("warped_floor_roots", WarpedFloorRootsBlock::new);
		CHORUS_GRASS = REGISTRY.register("chorus_grass", ChorusGrassBlock::new);
		CHORUS_LOG = REGISTRY.register("chorus_log", ChorusLogBlock::new);
		CHORUS_WOOD = REGISTRY.register("chorus_wood", ChorusWoodBlock::new);
		CHORUS_PLANKS = REGISTRY.register("chorus_planks", ChorusPlanksBlock::new);
		CHORUS_LEAVES = REGISTRY.register("chorus_leaves", ChorusLeavesBlock::new);
		CHORUS_STAIRS = REGISTRY.register("chorus_stairs", ChorusStairsBlock::new);
		CHORUS_SLAB = REGISTRY.register("chorus_slab", ChorusSlabBlock::new);
		CHORUS_FENCE = REGISTRY.register("chorus_fence", ChorusFenceBlock::new);
		CHORUS_FENCE_GATE = REGISTRY.register("chorus_fence_gate", ChorusFenceGateBlock::new);
		CHORUS_PRESSURE_PLATE = REGISTRY.register("chorus_pressure_plate", ChorusPressurePlateBlock::new);
		CHORUS_BUTTON = REGISTRY.register("chorus_button", ChorusButtonBlock::new);
		CHORUS_VINES = REGISTRY.register("chorus_vines", ChorusVinesBlock::new);
		CHORUS_BLOSSOM_GRASS = REGISTRY.register("chorus_blossom_grass", ChorusBlossomGrassBlock::new);
		CHORUS_PLANT = REGISTRY.register("chorus_plant", ChorusPlantBlock::new);
		TALL_CHORUS_PLANT = REGISTRY.register("tall_chorus_plant", TallChorusPlantBlock::new);
		CHORUS_SHROOM = REGISTRY.register("chorus_shroom", ChorusShroomBlock::new);
		TALL_CHORUS_BLOSSOM_GRASS = REGISTRY.register("tall_chorus_blossom_grass", TallChorusBlossomGrassBlock::new);
		ENDERITE_ORE = REGISTRY.register("enderite_ore", EnderiteOreBlock::new);
		TITANIUM_ORE = REGISTRY.register("titanium_ore", TitaniumOreBlock::new);
		COMMPREST_VOID = REGISTRY.register("commprest_void", CommprestVoidBlock::new);
		CRACKED_ENDSTONE_BRICKS = REGISTRY.register("cracked_endstone_bricks", CrackedEndstoneBricksBlock::new);
		CHISELED_ENDSTONE_BRICKS = REGISTRY.register("chiseled_endstone_bricks", ChiseledEndstoneBricksBlock::new);
		ENDSTONE_TILES = REGISTRY.register("endstone_tiles", TilesEndstoneBricksBlock::new);
		POLISHED_ENDSTONE = REGISTRY.register("polished_endstone", PolishedEndstoneBlock::new);
		ENDSTONE_PILLAR = REGISTRY.register("endstone_pillar", EndstonePillarBlock::new);
		ARCH_ENDSTONE_PILLAR = REGISTRY.register("arch_endstone_pillar", ArchEndstonePillarBlock::new);
		SMOOTH_PURPUR = REGISTRY.register("smooth_purpur", SmoothPurpurBlock::new);
		CRACKED_PURPUR = REGISTRY.register("cracked_purpur", CrackedPurpurBlock::new);
		PURPUR_TILES = REGISTRY.register("purpur_tiles", PurpurTilesBlock::new);
		CUBET_PURPUR_TILES = REGISTRY.register("cubet_purpur_tiles", CubetPurpurTilesBlock::new);
		CHISELED_PURPUR = REGISTRY.register("chiseled_purpur", ChiseledPurpurBlock::new);
		PURPUR_WALL = REGISTRY.register("purpur_wall", PurpurWallBlock::new);
		END_CITY_VAULT = REGISTRY.register("end_city_vault", EndCityVaultBlock::new);
		END_SPAWNER = REGISTRY.register("end_spawner", EndSpawnerBlock::new);
		END_FIRE = REGISTRY.register("end_fire", EndFireBlock::new);
		METEOR_DEBRIS = REGISTRY.register("meteor_debris", MeteorDebrisBlock::new);
		TITANIUM_PEDESTAL = REGISTRY.register("titanium_pedestal", TitaniumPedestalBlock::new);
		TITANIUM_BLOCK = REGISTRY.register("titanium_block", TitaniumBlockBlock::new);
		SHADOW_GRASS = REGISTRY.register("shadow_grass", ShadowGrassBlock::new);
		PILLARS_OF_SHADOW_WOOD = REGISTRY.register("pillars_of_shadow_wood", PillarsOfShadowWoodBlock::new);
		UNKNOWN_BLOCK = REGISTRY.register("unknown_block", UnknownBlockBlock::new);
		DRAGON_FRUIT_GROW = REGISTRY.register("dragon_fruit_grow", DragonFruitGrowBlock::new);
		DRACORA_PALM_LOG = REGISTRY.register("dracora_palm_log", DracoraPalmLogBlock::new);
		DRACORA_PALM_WOOD = REGISTRY.register("dracora_palm_wood", DracoraPalmWoodBlock::new);
		DRACORA_PALM_PLANKS = REGISTRY.register("dracora_palm_planks", DracoraPalmPlanksBlock::new);
		DRACORA_PALM_LEAVES = REGISTRY.register("dracora_palm_leaves", DracoraPalmLeavesBlock::new);
		DRACORA_PALM_STAIRS = REGISTRY.register("dracora_palm_stairs", DracoraPalmStairsBlock::new);
		DRACORA_PALM_SLAB = REGISTRY.register("dracora_palm_slab", DracoraPalmSlabBlock::new);
		DRACORA_PALM_FENCE = REGISTRY.register("dracora_palm_fence", DracoraPalmFenceBlock::new);
		DRACORA_PALM_FENCE_GATE = REGISTRY.register("dracora_palm_fence_gate", DracoraPalmFenceGateBlock::new);
		DRACORA_PALM_PRESSURE_PLATE = REGISTRY.register("dracora_palm_pressure_plate", DracoraPalmPressurePlateBlock::new);
		DRACORA_PALM_BUTTON = REGISTRY.register("dracora_palm_button", DracoraPalmButtonBlock::new);
		DRACORA_GRASS = REGISTRY.register("dracora_grass", DracoraGrassBlock::new);
		MOSSY_ENDSTONE_BRICKS = REGISTRY.register("mossy_endstone_bricks", MossyEndstoneBricksBlock::new);
		CRACKED_CHORUS_PLANKS = REGISTRY.register("cracked_chorus_planks", CrackedChorusPlanksBlock::new);
		DIRTY_CHORUS_PLANKS = REGISTRY.register("dirty_chorus_planks", DirtyChorusPlanksBlock::new);
		CORN_STAGE_0 = REGISTRY.register("corn_stage_0", CornStage0Block::new);
		CORN_STAGE_1 = REGISTRY.register("corn_stage_1", CornStage1Block::new);
		CORN_STAGE_2 = REGISTRY.register("corn_stage_2", CornStage2Block::new);
		CORN_STAGE_3 = REGISTRY.register("corn_stage_3", CornStage3Block::new);
		HOLE_IN_REALITY = REGISTRY.register("hole_in_reality", HoleInRealityBlock::new);
		UNSTABLE_HOLE_IN_REALITY = REGISTRY.register("unstable_hole_in_reality", UnstableHoleInRealityBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}